# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic method for the imzMLreader
NULL

#' Generic method for the imzMLreader
#' testingimzMLBinRead
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param read_mz: if true m/z data is readed, otherwise intensities are readed.
#' @param continuous: true if imzML data is in continuous mode
NULL

imzMLBinReadAllMz <- function(ibdFname, imzML) {
    .Call('_rPPGAS_imzMLBinReadAllMz', PACKAGE = 'rPPGAS', ibdFname, imzML)
}

#' Testing the imzMLwriter in sequential mode
#' This function creates a new ibd file with the provided data descibed in the following params
#' @param ibdFname: full path to the ibd file.
#' @param mz_dataTypeString: String to specify the data format used to encode m/z values.
#' @param int_dataTypeString: String to specify the data format used to encode intensity values.
#' @param uuid: 16 bytes long UUID.
#' @param mzArray: A matrix with the m/z values for all pixels. Each pixel corresponds to a row. If there is only one row data will be saved in continuous mode
#' @param intArray: A matrix with the intensity values for all pixels. Each pixel corresponds to a row so the number of pixels is extracted from here.
.debug_imzMLBinWriterSequential <- function(ibdFname, mz_dataTypeString, int_dataTypeString, str_uuid, mzArray, intArray) {
    .Call('_rPPGAS_testingimzMLBinWriteSequential', PACKAGE = 'rPPGAS', ibdFname, mz_dataTypeString, int_dataTypeString, str_uuid, mzArray, intArray)
}

#' CimzMLBinCreateNewIBD.
#' This function creates a new ibd file with the provided uuid
#' @param ibdFname: full path to the ibd file.
#' @param uuid: 16 bytes long UUID.
CimzMLBinCreateNewIBD <- function(ibdFname, str_uuid) {
    invisible(.Call('_rPPGAS_CimzMLBinCreateNewIBD', PACKAGE = 'rPPGAS', ibdFname, str_uuid))
}

#' CimzMLBinAppendMass.
#' This function appends a new mass axis to a given ibd file.
#' The last added offset is returned.
#' @param ibdFname: full path to the ibd file.
#' @param mz_dataTypeString:  String to specify the data format used to encode m/z values.
#' @param mzNew: The mass axis to append.
CimzMLBinAppendMass <- function(ibdFname, mz_dataTypeString, mzNew) {
    .Call('_rPPGAS_CimzMLBinAppendMass', PACKAGE = 'rPPGAS', ibdFname, mz_dataTypeString, mzNew)
}

#' CimzMLBinAppendIntensity.
#' This function appends a new mass axis to a given ibd file.
#' The last added offset is returned.
#' @param ibdFname: full path to the ibd file.
#' @param int_dataTypeString:  String to specify the data format used to encode m/z values.
#' @param intNew: The mass axis to append.
CimzMLBinAppendIntensity <- function(ibdFname, int_dataTypeString, intNew) {
    .Call('_rPPGAS_CimzMLBinAppendIntensity', PACKAGE = 'rPPGAS', ibdFname, int_dataTypeString, intNew)
}

#' A method to use the imzMLwriter in modify mode to allow direct modification of mass axes for the calibration
#' This function modifies data of an ibd file with the following params
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param mz_dataTypeString: String to specify the data format used to encode m/z values.
#' @param int_dataTypeString: String to specify the data format used to encode intensity values.
#' @param continuous: true if imzML data is in continuous mode
#' @param mzNew: A vector with the m/z values. Must be the same length as the original imzML mass target massa axis.
#' @param mzOffset: offset in the ibd file of the target mass axis.
CimzMLBinWriteModifyMass <- function(ibdFname, NPixels, mz_dataTypeString, int_dataTypeString, continuous, mzNew, mzOffset) {
    invisible(.Call('_rPPGAS_CimzMLBinWriteModifyMass', PACKAGE = 'rPPGAS', ibdFname, NPixels, mz_dataTypeString, int_dataTypeString, continuous, mzNew, mzOffset))
}

#' CimzMLBinReadMass.
#' 
#' Reads a single mass axis from the imzML file.
#' 
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param continuous: true if imzML data is in continuous mode
CimzMLBinReadMass <- function(ibdFname, NPixels, N, offset, dataTypeString, continuous) {
    .Call('_rPPGAS_CimzMLBinReadMass', PACKAGE = 'rPPGAS', ibdFname, NPixels, N, offset, dataTypeString, continuous)
}

#' CimzMLBinReadIntensity.
#' 
#' Reads a single mass axis from the imzML file.
#' 
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param continuous: true if imzML data is in continuous mode
CimzMLBinReadIntensity <- function(ibdFname, NPixels, N, offset, dataTypeString, continuous) {
    .Call('_rPPGAS_CimzMLBinReadIntensity', PACKAGE = 'rPPGAS', ibdFname, NPixels, N, offset, dataTypeString, continuous)
}

#' Method to read a peak list from an imzML file. Processed mode is assumed.
#' testingimzMLBinRead
#' @param ibdFname: full path to the ibd file.
#' @param imzML_peakList_descriptor: imzML file description as it is returned by the CimzMLParse() function.
#' @param PixelID: the pixel ID to read a peak list.
CimzMLReadPeakList <- function(ibdFname, imzML_peakList_descriptor, PixelID) {
    .Call('_rPPGAS_CimzMLReadPeakList', PACKAGE = 'rPPGAS', ibdFname, imzML_peakList_descriptor, PixelID)
}

#' Method to overwrite the UUID of an imzML ibd file.
#' testingimzMLBinRead
#' @param ibdFname: full path to the ibd file.
#' @param newUUID: the new uuid as a string.
overwriteIbdUUid <- function(ibdFname, newUUID) {
    invisible(.Call('_rPPGAS_overwriteIbdUUid', PACKAGE = 'rPPGAS', ibdFname, newUUID))
}

#' Cload_imzMLSpectra
#' Load spectra into a Matrix object interpolating to the common mass axis when necessary.
#' @param rMSIobj: an rMSI object prefilled with a parsed imzML.
#' @param pixelIDs: pixel ID's of the spectra to load in C-style indexing (starting at 0).
#' @param commonMassAxis: a common mass axis that may be different than the mass axis in the rMSI object.
#' @param number_of_threads: number of thread to use during interpolation
Cload_imzMLSpectra <- function(rMSIobj, pixelIDs, commonMassAxis, number_of_threads) {
    .Call('_rPPGAS_Cload_imzMLSpectra', PACKAGE = 'rPPGAS', rMSIobj, pixelIDs, commonMassAxis, number_of_threads)
}

#' Cload_imzMLImages
#' Load images
#' @param rMSIobj: an rMSI object prefilled with a parsed imzML.
#' @param pixelIDs: pixel ID's of the spectra to load in C-style indexing (starting at 0).
#' @param maxIndex: mass index range to load
#' @param commonMassAxis: a common mass axis that may be different than the mass axis in the rMSI object.
#' @param number_of_threads: number of thread to use during interpolation
#' @Return a matrix
#' 
Cload_imzMLImages <- function(rMSIobj, pixelIDs, massIndex, commonMassAxis, number_of_threads) {
    .Call('_rPPGAS_Cload_imzMLImages', PACKAGE = 'rPPGAS', rMSIobj, pixelIDs, massIndex, commonMassAxis, number_of_threads)
}

CimzMLParse <- function(xml_path) {
    .Call('_rPPGAS_CimzMLParse', PACKAGE = 'rPPGAS', xml_path)
}

CimzMLStore <- function(fname, imgInfo, mass_spectrometer_file_format = "rMSI exported imzML") {
    .Call('_rPPGAS_CimzMLStore', PACKAGE = 'rPPGAS', fname, imgInfo, mass_spectrometer_file_format)
}

#'  peakMatrix() link with R.
#'  converts the info in the imzML file into a peak matrix.
#' 
#'  @param ibdFname  absolute reference to the file with the ibd extension.
#'  @param imzML  list with information extracted from the imzML file with import_imzML()
#'  @param params specific parameters
#'   "SNR": signal-to-noise ratio
#'   "minPixelsSupport": minimum percentage of pixels that must support an ion for it to be considered.
#'   "massResolution": mass resolution with which the spectra were acquired.
#'   "maxMassResolution": maximum desired mass resolution.
#'   "noiseMethod": method for estimating noise.
#'  @param mzLow  lower mass to consider
#'  @param mzHigh higher mass to consider
#'  @nThreads number of threads suggested for parallel processing.
#'  @return lista: peakMatrix, massVector, pixelsSupport
#'     peakMatrix: matrix of centroids and the intensity associated with each pixel.
#'     massVector: the mz associated with each column of peakmatrix.
#'     pixelsSupport: number of pixels with intensity > 0
NULL

peakMatrix <- function(ibdFname, imzML, params, mzLow, mzHigh, nThreads) {
    .Call('_rPPGAS_peakMatrix', PACKAGE = 'rPPGAS', ibdFname, imzML, params, mzLow, mzHigh, nThreads)
}

